version: "3.8"


x-mock-shared-vars: &mock-shared-vars
  CHAN_HOST: https://a.4cdn.org

services:

  live-python:
    build: ./python
    command: flask --app main run --debug --host=0.0.0.0
    ports:
      - "8001:5000"
    volumes:
      - ./python/src:/app
    environment:
      <<: *mock-shared-vars
