version: "3.8"


x-mock-shared-vars: &mock-shared-vars
  CHAN_HOST: https://a.4cdn.org

services:

  live-python:
    build: ./python
    command: flask --app main run --debug --host=0.0.0.0
    ports: [8001:5000]
    volumes: [./python/src:/app]
    environment:
      <<: *mock-shared-vars

  live-go:
    build: 
      context: ./go
      target: dev
    command: ["CompileDaemon", "-directory=/app/", "-polling", "-build=go build -a -tags netgo -o ./service", "-command=/app/service"]
    ports: [8002:8080]
    volumes: [./go/src:/app]
    environment:
      <<: *mock-shared-vars
    
  live-javascript:
    build: ./javascript
    command: nodemon --legacy-watch src/index.js
    init: true
    ports: [8003:3000]
    volumes: [./javascript/src:/app/src]
    environment:
      <<: *mock-shared-vars

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports: [9001:8080]
    environment:
      URL: "http://localhost:9002/swagger.yml"
    depends_on:
      - schema-host
      - live-python
      - live-go
  
  schema-host:
    build: ./schema
    volumes: [./schema:/app/public]
    ports: [9002:80]

