name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build the go Docker image
      run: |
        docker build . --file go/Dockerfile --tag glue-go:$(date +%s)
        docker push ghcr.io/dominickp/store:latest

    - name: Build the python Docker image
      run: |
        docker build . --file python/Dockerfile --tag glue-python:$(date +%s)
        docker push ghcr.io/dominickp/store:latest

    - name: Build the javascript Docker image
      run: |
        docker build . --file go/Dockerfile --tag glue-javascript:$(date +%s)
        docker push ghcr.io/dominickp/store:latest
