name: Docker Image CI

on:
  push:
    branches: [ "main", "test" ]
    # don't trigger if just updating docs
    paths-ignore:
      - "**.md"
  pull_request:
    branches: [ "main", "test" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    # Go image
    - name: Extract metadata (tags, labels) for Docker (go)
      id: meta-go
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-go
    - name: Build and push Docker image (go)
      uses: docker/build-push-action@v5
      with:
        context: ./go
        push: true
        platforms: linux/arm64
        tags: ${{ steps.meta-go.outputs.tags }}
        labels: ${{ steps.meta-go.outputs.labels }}
    # Python image
    - name: Extract metadata (tags, labels) for Docker (py)
      id: meta-py
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-py
    - name: Build and push Docker image (py)
      uses: docker/build-push-action@v5
      with:
        context: ./python
        push: true
        platforms: linux/arm64
        tags: ${{ steps.meta-py.outputs.tags }}
        labels: ${{ steps.meta-py.outputs.labels }}
    # Javascript image
    - name: Extract metadata (tags, labels) for Docker (js)
      id: meta-js
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-js
    - name: Build and push Docker image (js)
      uses: docker/build-push-action@v5
      with:
        context: ./javascript
        push: true
        platforms: linux/arm64
        tags: ${{ steps.meta-js.outputs.tags }}
        labels: ${{ steps.meta-js.outputs.labels }}

