name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Log in to the Container registry
      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
  
    - name: Build the go Docker image
      run: |
        docker build . --file go/Dockerfile --tag glue-go:$(date +%s)
        docker push ghcr.io/dominickp/store:latest

    - name: Build the python Docker image
      run: |
        docker build . --file python/Dockerfile --tag glue-python:$(date +%s)
        docker push ghcr.io/dominickp/store:latest

    - name: Build the javascript Docker image
      run: |
        docker build . --file go/Dockerfile --tag glue-javascript:$(date +%s)
        docker push ghcr.io/dominickp/store:latest
